on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main
jobs:
  build-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          requirements: 'requirements.txt'
          spec: 'vpx-settings-editor.spec'
          upload_exe_with_name: 'vpx-settings-editor-Linux-x86_64'
          options: --onefile, --noconsole, --name "vpx-settings-editor"

  build-macos-arm64:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create Executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.12'
          requirements: 'requirements.txt'
          spec: 'vpx-settings-editor.spec'
          upload_exe_with_name: 'vpx-settings-editor-macOS-arm64'
          options: --onefile, --noconsole, --name "vpx-settings-editor"
